Feature/vector output
blooop/bencher pull request #31
Opened 2023-06-16 08:39 UTC by blooop

Add support for plotting vector outputs.  Until now bencher has only operated on scalar inputs and outputs and due to the way it is stored in a structured xarray dataset it is difficult to unify the two modes of operation.  This pr creates a dictionary to store the vector results as they are currently incompatible with the scalar datatypes.   This pr only allows for 1D input sweeps and future work is to generalise this across N dimensions (to match the features of scalar inputs and outputs). 

This adds an example of how to use the vector outputs:
![image](https://github.com/dyson-ai/bencher/assets/1213400/81c310b0-54c7-44ea-b35b-6f3d55e3daf1)

![image](https://github.com/dyson-ai/bencher/assets/1213400/55f626d4-a0aa-4c44-8937-bca66f507b6a)

2023-06-19 08:03 UTC, mfinean commented on bencher/bench_vars.py
> +def hash_cust(var: any) -> str:
Naming of hash_cust and hash_custom is confusing/very close

2023-06-19 08:05 UTC, mfinean commented on bencher/bench_vars.py
> +    def hash_custom(self) -> str:
ParametrizedOutput and ParametrizedSweep have the same class definition - are we able to remove duplication here?

2023-06-19 08:06 UTC, mfinean commented on bencher/bench_vars.py
> +        # self.
Remove commented lines

2023-06-19 08:08 UTC, mfinean commented on bencher/bencher.py
>                      result_data = np.empty(dims_cfg.dims_size)
np.empty followed by a fill can be done together with  
`np.full( *SHAPE*, *VALUE*)`

2023-06-19 08:12 UTC, mfinean requested changes
Main comments are with respect to class duplication and updated naming for the 'hash_custom'-type functions to make it clearer what these are/when they're used

2023-06-19 08:20 UTC, blooop commented on bencher/bench_vars.py
> +    def hash_custom(self) -> str:
I was planning on doing this in a separate pr cos it involves a large find/replace operation.

#32

2023-06-19 08:25 UTC, blooop commented on bencher/bench_vars.py
> +def hash_cust(var: any) -> str:
hash_cust -> hash_sha1
has_custom -> hash_persistent

2023-06-20 07:41 UTC, mfinean approved these changes

2023-06-20 07:42 UTC, merged