Feature/plot sig
blooop/bencher pull request #35
Opened 2023-06-21 17:46 UTC by blooop

2023-06-22 14:44 UTC, mfinean commented on bencher/bench_cfg.py
> +    # def as_sns_args(self) -> dict:
Should this commented code be removed?

2023-06-22 14:44 UTC, mfinean commented on bencher/plotting/plot_collection.py
> +            plotter_class_instance (PlotProvider): A class that contains plotting methods
Can also add to docstring

Raises:
    ValueError: Explanation here.

2023-06-22 14:44 UTC, mfinean commented on bencher/plotting/plot_collection.py
> +        for p in self.plotters.values():
p used as tmp variable for nested loops looks confusing

2023-06-22 14:44 UTC, mfinean commented on bencher/plotting/plot_filter.py
> +        if val >= 0:
This might look clearer if we have         

`if val < 0:
raise ValueError("val must be >= 0")

...
return lower_match and upper_match
`

2023-06-22 14:44 UTC, mfinean commented on bencher/plotting/plot_library.py
> +        for pt in [p for p in PlotTypes]:  # iterate through all plot enums
This looks like it can be simplified to

`for pt in PlotTypes:`

2023-06-22 14:44 UTC, mfinean commented on bencher/plotting/plots/tables.py
> +    def dataframe_flat(self, pl_in: PlotInput) -> List[pn.panel]:
What's the reason for returning as a list (with 1 entry in all)?

2023-06-22 14:44 UTC, mfinean commented on test/test_plot_collection.py
> +        assert len(plot_coll.plotters) == 0
plot_coll could probably do with a method like get_num_plots()?

2023-06-22 14:55 UTC, blooop commented on test/test_plot_collection.py
> +        assert len(plot_coll.plotters) == 0
I don't need to know the number of plots in general. this is just a test to assert that add and remove works properly

2023-06-22 14:56 UTC, blooop commented on bencher/plotting/plots/tables.py
> +    def dataframe_flat(self, pl_in: PlotInput) -> List[pn.panel]:
The plot providers can return between 0 and N plots.  By always returning a list I can combine the results of all the plot providers without needed checks for None return values.

2023-06-22 15:30 UTC, blooop commented on bencher/plotting/plot_collection.py
> +        for p in self.plotters.values():
fixed:

for plt_fn in self.plotters.values():
            plots = plt_fn(PlotInput(bench_cfg, rv, plt_cnt_cfg))
            for plt_instance in plots:
                tabs.append(plt_instance)

2023-06-23 06:43 UTC, mfinean requested changes

2023-06-23 06:43 UTC, mfinean commented on bencher/plotting/plot_filter.py
> +        if val >= 0:
if val >= 0 is no longer needed since the complement is caught in the previous if

2023-06-23 07:12 UTC, mfinean approved these changes

2023-06-23 07:13 UTC, merged